name: farmtrack
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.1
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase y otras dependencias
  firebase_core: ^3.5.0
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.1.0
  firebase_storage: ^12.1.0  # ðŸ“¦ Para subir imÃ¡genes a Firebase Storage
  image_picker: ^1.1.2       # ðŸ“· Para seleccionar imÃ¡genes de la galerÃ­a o cÃ¡mara

  # ðŸ‘‡ Otras librerÃ­as del proyecto
  provider: ^6.1.2
  material_design_icons_flutter: ^7.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
